{{- if .Values.hpa.enabled -}}
# @formatter:off
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "base-chart.fullname" . }}
  labels:
{{ include "base-chart.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "base-chart.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas | default .Values.replicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.coolDownPeriod | default 300 }}
  metrics:
    {{- if .Values.hpa.external }}
    - type: External
      external:
        metric:
          name: {{ .Values.hpa.external.metricName }}
          selector:
            matchLabels:
              {{- range $key, $value := .Values.hpa.external.matchLabels }}
              {{ $key }}: {{ $value | quote }}
              {{- end }}
        target:
          type: Value
          averageValue: {{ .Values.hpa.external.targetValue }}
    {{- end }}
    {{- if .Values.hpa.externalExtra }}
    - type: External
      external:
        metric:
          name: {{ .Values.hpa.externalExtra.metricName }}
          selector:
            matchLabels:
              {{- range $key, $value := .Values.hpa.externalExtra.matchLabels }}
              {{ $key }}: {{ $value | quote }}
              {{- end }}
        target:
          type: Value
          averageValue: {{ .Values.hpa.externalExtra.targetValue }}
    {{- end }}
    {{- if .Values.hpa.custom }}
    - type: Object
      object:
        metric:
          name: {{ .Values.hpa.custom.metricName }}
        describedObject:
          apiVersion: {{ include "base-chart.ingress.apiVersion" . }}
          kind: {{ .Values.hpa.custom.objectKind }}
          name: {{ .Values.hpa.custom.objectName }}
        target:
          type: Value
          value: {{ .Values.hpa.custom.targetValue }}
    {{- end }}
    {{- if .Values.hpa.cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.cpu }}
    {{- end }}
    {{- if .Values.hpa.memory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.memory }}
    {{- end }}
{{- end }}
