{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pghero.fullname" . }}
  labels:
{{ include "pghero.labels" . | indent 4 }}
data:
  pghero.yml: |-
{{ .Values.config | indent 4 }}
{{- end }}