apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gradle-build-cache-node.fullname" . }}
  labels:
    app: {{ template "gradle-build-cache-node.name" . }}
    chart: {{ template "gradle-build-cache-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gradle-build-cache-node.name" . }}
      release: {{ .Release.Name }}
{{- with .Values.deploymentStrategy }}
  strategy:
{{ toYaml . | trim | indent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ template "gradle-build-cache-node.name" . }}
        release: {{ .Release.Name }}
      annotations:
        {{- if not .Values.existingConfigMap }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      initContainers:
        - name: {{ .Chart.Name }}-config-mounter
          image: {{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}
          imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
          command: [
              "sh",
              "-ce",
              "cp /tmp/config.yaml /data/conf/config.yaml" ]
          volumeMounts:
            - name: configmap
              mountPath: /tmp/config.yaml
              subPath: config.yaml
            - name: build-cache-config-dir
              mountPath: /data/conf
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              protocol: TCP
              containerPort: 5071
          livenessProbe:
            {{- toYaml .Values.livenessProbe | trim | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | trim | nindent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: build-cache-config-dir
              mountPath: /data/conf
            {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
            {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      {{- if eq .Values.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "{{ .Values.podAntiAffinityTopologyKey }}"
              labelSelector:
                matchLabels:
                  app: {{ template "gradle-build-cache-node.name" . }}
                  release: {{ .Release.Name }}
      {{- else if eq .Values.podAntiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: "{{ .Values.podAntiAffinityTopologyKey }}"
                labelSelector:
                  matchLabels:
                    app: {{ template "gradle-build-cache-node.name" . }}
                    release: {{ .Release.Name }}
      {{- end }}
      volumes:
        - name: build-cache-config-dir
          emptyDir: {}
        - name: configmap
          configMap:
            name: {{ template "gradle-build-cache-node.fullname" . }}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "gradle-build-cache-node.fullname" . }}{{- end }}
          {{- else }}
          emptyDir: {}
          {{- end  }}
        {{- if .Values.extraVolumes }}
  {{ toYaml .Values.extraVolumes | indent 8 }}
        {{- end }}
