# @formatter:off
apiVersion: v1
kind: Service
metadata:
  name: {{ template "gradle-build-cache-node.fullname" . }}
  labels:
    app: {{ template "gradle-build-cache-node.name" . }}
    chart: {{ template "gradle-build-cache-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "gradle-build-cache-node.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
