{{- if and .Values.databaseUrl (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pghero.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "pghero.labels" . | nindent 4 }}
type: Opaque
data:
  pghero-database-url: {{ include "pghero.databaseUrl" . | b64enc | quote }}
{{- end -}}
